fix(ec): shift before processing to avoid shift missed on continue

diff --git a/.local/bin/ec b/.local/bin/ec
--- a/.local/bin/ec
+++ b/.local/bin/ec
@@ -3,9 +3,11 @@
 count=$#
 while [ "$count" -ne 0 ]; do
   count=$((count - 1))
+  arg=$1
+  shift
 
-  if ! f=$(command -v "$1"); then
-    printf "%s not found\n" "$1" >&2
+  if ! f=$(command -v "$arg"); then
+    printf "%s not found\n" "$arg" >&2
     continue
   fi
 
@@ -14,11 +16,9 @@ while [ "$count" -ne 0 ]; do
       set -- "$@" "$f"
       ;;
     *)
-      printf "%s not found\n" "$1" >&2
+      printf "%s not found\n" "$arg" >&2
       ;;
   esac
-
-  shift
 done
 
 if [ "$#" -eq 0 ]; then
