fix(llm-chat): fix typo in save message

diff --git a/.local/bin/llm-chat b/.local/bin/llm-chat
--- a/.local/bin/llm-chat
+++ b/.local/bin/llm-chat
@@ -268,7 +268,7 @@ save_session() {
 
   if ! cp -- "$conversation" "$1" || \
     ! cat -- "$persistent_fileids" "$volatile_fileids" >"$2"; then
-    printf "fialed to save as %s and %s\n" "$1" "$2" >&2
+    printf "failed to save as %s and %s\n" "$1" "$2" >&2
   fi
   return 0
 }
