fix(stpl): allow EOF as substitution expression

diff --git a/.local/bin/stpl b/.local/bin/stpl
--- a/.local/bin/stpl
+++ b/.local/bin/stpl
@@ -36,9 +36,13 @@ expand_line() {
           exit 1
         fi
 
-        stpl_cmd=$'stpl_result=$(cat <<EOF\n'"$stpl_expr"$'\nEOF\n) && printf "%s" "$stpl_result"'
-        if ! command eval "$stpl_cmd" 2>/dev/null; then
-          error "failed to do here-doc word expansion for: %s" "$stpl_expr"
+        if [ "$stpl_expr" = EOF ]; then
+          printf "EOF"
+        else
+          stpl_cmd=$'stpl_result=$(cat <<EOF\n'"$stpl_expr"$'\nEOF\n) && printf "%s" "$stpl_result"'
+          if ! command eval "$stpl_cmd" 2>/dev/null; then
+            error "failed to do here-doc word expansion for: %s" "$stpl_expr"
+          fi
         fi
         ;;
       *)
