refactor(setup-dotfiles): move deps check logic to each script

diff --git a/.config/setup-dotfiles/50-neovim b/.config/setup-dotfiles/50-neovim
--- a/.config/setup-dotfiles/50-neovim
+++ b/.config/setup-dotfiles/50-neovim
@@ -11,6 +11,24 @@ if [ -e nvim ]; then
   return
 fi
 
-git clone https://github.com/kevin0x0/nvim
+check_deps() {
+  helper_check_deps error "the following commands are required for pulling neovim config" <<'EOF'
+git the stupid content tracker
+EOF
+}
+
+check_deps || error_exit "stopped"
+
+repo_url=https://github.com/kevin0x0/nvim
+if ! git clone "$repo_url"; then
+  error_exit "failed to clone $repo_url"
+fi
+
+helper_check_deps warning "the following commands are required by neovim config" <<'EOF'
+git the stupid content tracker
+tree-sitter cli for tree-sitter, a incremental parsing library
+EOF
+
+return 0
 
 # vim: ft=sh
diff --git a/.config/setup-dotfiles/50-sway b/.config/setup-dotfiles/50-sway
--- a/.config/setup-dotfiles/50-sway
+++ b/.config/setup-dotfiles/50-sway
@@ -1,4 +1,12 @@
-# Create wall paper directories for sway
+# Create wall paper symlink for sway
+
+check_deps() {
+  helper_check_deps error "the following commands are required for creating wallpaper symlink for sway:" <<'EOF'
+xdg-user-dir find an XDG user dir
+EOF
+}
+
+check_deps || error_exit "stopped"
 
 current=$(xdg-user-dir PICTURES)/sway-current-wallpaper
 if [ -e "$current" ]; then
@@ -7,5 +15,25 @@ if [ -e "$current" ]; then
 fi
 
 ln -sf -- /dev/null "$current"
+
+helper_check_deps warning "the following commands are required for running sway:" <<'EOF'
+swaymsg sway cli
+swaybg wallpaper tool
+firefox browser
+i3status bar
+wmenu dynamic menu for wayland
+wmenu-run app launcher
+foot terminal emulator
+grim screenshot utility
+slurp screen region selector
+mako notification daemon
+makoctl mako cli
+swayimg image viewer
+brightnessctl brightness control tool
+xdg-user-dir XDG user directory getter
+pkill kill processes by name
+EOF
+
+return 0
 
 # vim: ft=sh
